version: 2
updates:
    - package-ecosystem: "npm" # See documentation for possible values
      directory: "/frontend" # Location of package manifests
      schedule:
          interval: "weekly"
    - package-ecosystem: "npm" # See documentation for possible values
      directory: "/backend" # Location of package manifests
      schedule:
          interval: "weekly"
    - package-ecosystem: "docker"
      directory: "/frontend"
      schedule:
          interval: "weekly"
    - package-ecosystem: "docker"
      directory: "/backend"
      schedule:
          interval: "weekly"
