/** @type {import('next').NextConfig} */

import transpile from "next-transpile-modules";
import axios from "axios";
import qs from "qs";

const withTM = transpile(["react-icons/fa", "react-icons/lib"]);

const backendBaseUrl =
    process.env.BACKEND_URL ?? process.env.NEXT_PUBLIC_BACKEND_URL ?? "";
const backend = axios.create({
    baseURL: `${backendBaseUrl}/api`,
    paramsSerializer: {
        serialize: (params) =>
            qs.stringify(params, { arrayFormat: "brackets" }),
    },
});

const postsToRedirect = [
    "samen-tegen-racisme",
    "onderwijs-in-actie",
    "klimaatmars",
    "meer-dan-10-000-scholieren-eisen-klimaatactie",
    "staken-voor-het-klimaat",
    "staak-7-februari-mee-voor-het-klimaat",
    "weekend-vol-scholing-activisme-en-gezelligheid",
    "rood-weekend",
    "race-voor-een-betaalbaar-huis",
    "mannenliefde-met-van-der-staaij",
    "rechter-oordeelt-deliveroo-maakt-van-koeriers-schijnzelfstandigen",
    "historische-staking-voor-ons-onderwijs",
    "kom-26-en-27-januari-naar-het-rood-weekend",
    "onze-toekomst-gaat-boven-hun-winst-2",
    "eerste-ledenvergadering-2019",
    "jubileum-rood",
    "nieuwe-ledenavond",
    "zomerschool-2019-in-aantocht",
    "rood-viert-dag-van-de-arbeid",
    "vechtvoor14",
    "sta-op-voor-je-rechten-op-1-mei",
    "kom-naar-de-nieuwe-ledenavond",
    "vredesdag-2019",
    "kom-naar-de-vredesdag",
    "winsten-boven-mensenlevens",
    "nominaties-voor-de-huisjesmelker-van-het-jaar-verkiezing",
    "kom-naar-de-vredesdag-2",
    "in-memoriam-ami-gest-1989-2019",
    "succes-aanpak-van-vastgoedbazen-met-woekerwinsten-een-stap-dichterbij",
    "rood-aanwezig-bij-grootste-nederlandse-klimaatmars-ooit",
    "loop-mee-met-rood-voor-het-klimaat",
    "van-haga-genomineerd-voor-huisjesmelker-van-het-jaar",
    "klimaatstakingen-gaan-door-doe-mee",
    "kom-naar-de-rood-sweet-16-op-18-mei",
    "rood-roept-duo-uit-tot-fiod-junior",
    "maak-kennis-met-rood-tijdens-de-introductieweken",
    "drukbezochte-dont-iraq-iran-avond",
    "scholing-hitte-en-gezelligheid-tijdens-zomerschool-2019",
    "rood-zomerschool-2019-is-begonnen",
    "een-schooljaar-vol-actie",
    "rood-op-parkpop",
    "facebook-put-your-money-where-your-mouth-is",
    "weg-met-de-schuldenberg",
    "huurders-van-nederland-verenigt-u",
    "drukbezochte-ledenvergadering-kiest-nieuw-bestuur",
    "marcel-van-hooijdonk-voor-de-tweede-keer-huisjesmelker-van-het-jaar",
    "rood-viert-16-jarig-bestaan",
    "laat-brussel-niet-de-baas-zijn-stem-morgen-sp",
    "over-de-streep-voor-de-basisbeurs",
    "shell-je-tijd-is-op",
    "ron-meyer-inspireert-tijdens-nieuwe-ledenavond",
    "voetbal-is-van-ons-2",
    "pensioenakkoord-geen-generatiestrijd-maar-klassenstrijd-2",
    "wij-eisen-onze-wereld-op-2",
    "rood-weekend-2020-een-succes",
    "geen-oorlog-met-iran",
    "manifestatie-geen-oorlog-met-iran",
    "nieuwe-rood-groep-in-zutphen",
    "mensenrechtenavond-met-de-moedigste-vrouw-van-afghanistan-malalai-joya",
    "kom-naar-het-rood-weekend",
    "actieteam-niet-in-mijn-naam-van-start",
    "rood-ledenvergadering-maakt-plannen-voor-2020-en-kiest-bestuursleden",
    "rood-ondertekent-manifest-tegen-jeugdloon",
    "kom-naar-politiek-cafe",
    "sp-afdelingen-kleuren-rood",
    "riseup4rojava",
    "overal-actie-voor-compensatie-voor-de-schuldengeneratie",
    "minister-blok-schoothond-van-trump-of-waakhond-van-vrede",
    "lokale-bijeenkomsten-van-start-wij-zijn-geen-proefkonijn",
    "kom-vrijdag-27-september-naar-het-klimaatoverleg",
    "de-eerste-stap-is-gezet-compensatie-voor-de-schuldengeneratie",
    "wij-eisen-compensatie-voor-de-schuldengeneratie",
    "drukke-klimaatmars-tijdens-rotterdamse-wereldhavendagen",
    "engelshoven-komt-het-onderwijs-beroven",
    "algemene-ledenvergadering-28-juni",
    "kom-naar-de-online-vredesdag-2020",
    "inspirerende-blacklivesmatter-demonstraties-door-heel-het-land",
    "vergeet-hawija-niet",
    "dag-van-de-arbeid",
    "rood-bestuursleden-gezocht",
    "koningsdag-woningsdag",
    "laseractie-op-kantoor-vno-ncw",
    "ga-in-gesprek-met-mahir-alkaya",
    "rood-opent-meldpunt-werk-corona",
    "hoe-de-coronacrisis-de-slotervaart-wond-blootlegt",
    "geef-jongeren-geen-corona-schuld-huur-opschortingen-nu",
    "meld-je-aan-voor-de-rood-kandidatencommissie",
    "demonstreer-21-maart-online-mee-tegen-racisme",
    "lets-talk-about-war-in-pakhuis-de-zwijger",
    "ceta-vermindert-de-invloed-van-burgers-stop-het",
    "politiek-cafe-scholingen-scholingswerkgroep",
    "racisme-een-sluipmoordenaar-2",
    "corona-crisis-failliet-van-oude-politiek-2",
    "opinie-leve-de-democratische-republiek",
    "reactie-rood-op-berichten-rondom-ledenvergadering",
    "meld-je-aan-voor-de-rood-ledenvergadering",
    "stop-de-overvolle-treinen-schaf-de-eerste-klas-af",
    "%e2%80%8bdigitale-ledenvergadering-kiest-nieuw-bestuur",
    "update-belangrijke-stap-voor-internationaal-recht-tegen-annexatie-door-israel",
    "coalities-smeden-op-straat-niet-het-binnenhof-2",
    "verklaring-bestuur-m-b-t-stoppen-financiele-ondersteuning-sp",
    "een-nieuwe-website-nieuwe-hoop-op-een-gezamenlijke-oplossing",
    "camelot-of-scam-a-lot",
    "helden-hoeven-geen-salaris",
    "wij-gaan-door",
    "daders-toeslagenaffaire-moeten-consequenties-ondervinden-pak-de-echte-fraudeurs",
    "waarom-is-rood-op-aarde",
    "waarom-biedt-nederland-nog-onderdak-aan-amerikaanse-massavernietigingswapens",
    "autisme-zorg-in-nederland",
    "de-leeuwen-weg-uit-artis-een-goed-begin",
    "corona-problemen-van-studenten",
    "rood-is-het-nieuwe-groen-circulaire-beweging-amsterdam",
    "rood-rotterdam-toont-zich-solidair-met-de-voor14-bezetters",
    "tegen-het-pvda-gesponsorde-sloopbeleid",
    "rosa-luxemburg-na-honderd-jaar-nog-steeds-iconisch",
    "black-history-month-afrikaanse-revolutionair-patrice-lumumba",
    "rood-brengt-groet-aan-duitse-zusterorganisatie-eenheid-in-diversiteit-moet-onze-kracht-zijn",
    "rood-amsterdam-voert-actie-voor-14e-minimumloon",
    "black-history-month-angela-davis-vijand-van-de-staat-strijder-voor-de-onderdrukten",
    "rood-ledenvergadering-op-naar-een-vruchtbare-samenwerking",
    "rood-actiegroep-en-studentenbonden-compenseer-collegegeld-nu",
    "black-history-month-marielle-franco",
    "rood-utrecht-schrijft-samen-met-utrechtse-pjos-brief-aan-burgemeester-om-arrestaties-bij-xr-demonstratie",
    "pjo-debat-noord-brabant",
    "democratisering-van-de-huisvesting-dak-boven-het-hoofd-eten-op-tafel",
    "thales",
    "roodsuperzaterdag",
    "utrechtse-pjos-geen-extreemrechtse-geweldsverheerlijking-in-onze-stad",
    "alle-stemmen-tellen-mee",
    "hoe-nu-verder",
    "strijdbare-demonstraties-op-internationale-dag-tegen-racisme-en-discriminatie",
    "de-strijd-voor-een-studie-zonder-schulden",
    "patenten-op-medicijnen-moeten-worden-afgeschaft",
    "voor-een-leefbaar-minimumloon-voor14",
    "de-balans-van-lenin",
    "de-marxistische-scholingswerkgroep-wat-is-het-en-wat-doen-ze",
    "1-mei-dag-van-de-arbeid",
    "mayday-onze-klasse-bouwt-een-stormram",
    "rood-groningen-eert-verzetstrijders",
    "de-toespraak-van-olaf-kemerink-op-1-mei-in-nijmegen",
    "stop-de-voortdurende-cyclus-van-onrecht-in-palestina",
    "kom-naar-de-rood-zomerschool",
    "conclusies-van-de-rood-commissie-en-onze-reactie",
    "de-dood-van-eltjo-en-de-staking-van-1929",
    "55-klachten-over-woldring-verhuur-bv-ingediend-bij-meldpunt-ongewenst-verhuurgedrag",
    "reactie-rapport-commissie-kooijman",
    "ccn-overhandigt-zwartboek-aan-cvb-hanzehogeschool",
    "3-juni-studenten-staking-niet-mijn-schuld",
    "wij-gaan-helemaal-nergens-heen",
    "hoe-een-filantroop-het-volk-heeft-bestolen",
    "landelijke-studenten-staking-3-juni-sfeerimpressie",
    "de-bode-juni-2021-dijksma-schaft-het-demonstratierecht-af",
    "de-bode-juni-2021-sociaal-wonen-in-utrecht-niet-te-doen",
    "de-bode-juni-2021-aanmeldbeleid-van-basisscholen-bevordert-het-klasseverschil",
    "stukken-ledenvergadering-27-juni",
    "kritische-leden-zijn-betrokken-leden",
    "oproep-van-het-rood-bestuur-aan-de-partijraad-van-de-sp",
    "postnl-en-voor14",
    "pride-bij-rood-amsterdam",
    "wat-te-doen-met-rood",
    "verslag-ledenvergadering-27-juni",
    "de-bode-juli-2021-utrechtse-cultuursector-moet-plaatsmaken-voor-gentrificatie",
    "de-bode-juli-2021-weg-met-de-monarchie",
    "de-bode-juli-2021-gewone-man-genaaid-door-gentrificatie-overvecht",
    "de-bode-augustus-2021-noem-je-dat-vervoer-openbaar",
    "de-bode-augustus-2021-de-transitiezorg-is-aan-alle-kanten-ruk-de-strijd-voor-verbetering-is-hier",
    "de-bode-augustus-2021-amelisweerd-nog-steeds-in-gevaar",
    "politie-die-sleutels-heeft-van-studentenflats",
    "professionele-pretbedervers",
    "waalstrand-afgezet-afzetterij",
    "mosquitos-een-vijandige-oplossing-voor-een-structureel-probleem",
    "shelter-our-students-voert-actie-wegens-woningcrisis-in-groningen",
    "shelter-our-students-start-couchsurfing-initiatief",
    "verslag-rood-zomerschool-2021",
    "shelter-our-students-s-o-s-heeft-al-200-aanmeldingen",
    "concept-programma-rood",
    "van-woonbeleid-naar-wanbeleid-de-woningnood-in-nijmegen",
    "wat-willen-wij-schuldenvrij",
    "shelter-our-students-geeft-120-studenten-onderdak",
    "woonprotest",
    "verslag-bezetting-academiegebouw-shelter-our-students",
    "rood-gaat-internationaal",
    "eerste-adema-socialisten-borrel",
    "the-rood-to-power",
    "barinamiyoruz-wij-hebben-geen-onderdak",
    "waarom-vaush-uitnodigen-een-slecht-idee-was",
    "laat-vaush-spreken",
    "reactionairen-niet-welkom",
    "aankondiging-interim-rood-voorzitter",
    "de-bode-september-2021-gemeente-betaal-je-medewerkers-fatsoenlijk",
    "de-bode-september-2021-massale-verkrachtingen-onder-studenten-karige-hulp",
    "de-bode-september-2021-referendum-over-wooncrisis-moet-eerste-stap-zijn",
    "woonstrijd",
    "over-de-kwestie-vaush",
    "de-bode-oktober-2021-klimaatstaking-jaarbeursplein-geen-transitie-zonder-revolutie",
    "de-bode-oktober-2021-de-politie-bewijst-weer-de-knokploeg-van-de-bourgeoisie-te-zijn",
    "de-bode-oktober-2021-onteigen-huisjesmelkers",
    "rood-introduceert-steunlidmaatschappen",
    "rood-veroordeelt-politiegeweld",
    "de-adema-socialistenborrel",
    "tweede-versie-concept-programma-rood",
    "gezamenlijk-statement-rood-en-sp-tegen-de-heksenjacht-over-royementen",
    "huisjesmelker",
    "feitenrelaas-politiegeweld-op-het-woonopstand-in-rotterdam",
    "rood-groningen-de-straat-op-tegen-geweld-tegen-vrouwen",
    "verslag-ledenvergadering-21-november",
    "hoe-nu-verder-2",
    "de-bode-november-2021-21-november-woonprotest-utrecht",
    "de-bode-november-2021-op-hku-studenten-democratie-hard-nodig",
    "de-bode-november-2021-sp-top-royeert-oppositie-en-saboteert-plaatselijke-ledenvergadering",
    "gezamenlijke-verklaring-terugtrekking-uit-het-afdelingsbestuur-van-de-amsterdamse-afdeling-van-de-socialistische-partij",
    "de-strijd-voor-een-partij",
    "de-bode-december-2021-socialisten-laat-je-niet-splitsen",
    "de-bode-december-2021-op-naar-een-utrechtse-wooncoalitie",
    "de-bode-december-2021-wet-of-geen-wet-kraken-gaat-door",
    "de-rode-bode-de-socialisten-zijn-terug",
    "de-rode-bode-genoeg-is-genoeg",
    "ontmoet-de-zolderkamer-communisten",
    "stemmen",
    "verkiezingsfraude-om-huisjesmelkerschandpaal-te-ontlopen",
    "woonstrijd-groningen-gaat-door",
    "rood-internationale-werkgroep-update",
    "over-discipline-en-de-motie-van-afkeuring",
    "arina-amma-stopt-als-bestuurslid",
    "gediscrimineerde-huurders",
    "de-bode-januari-2022-een-gelukkig-en-strijdbaar-nieuwjaar",
    "de-bode-januari-2022-utrechtse-wooncrisis-rijst-de-pan-uit",
    "de-bode-januari-2022-de-woonrevolte-is-niet-klaar",
    "de-bode-februari-2022-de-emmer-is-vol-transzorg-nu",
    "de-bode-februari-2022-extreemrechts-is-niet-uteregs",
    "de-bode-februari-2022-stem-socialisten-utrecht",
    "wil-je-echt-dat-er-strenger-gestraft-wordt",
    "wachtlijsten-in-de-transzorg",
    "een-klein-beetje-van-alles-tegelijkertijd",
    "de-eisen-voor-internationale-werkende-vrouwendag",
    "een-pleidooi-voor-factierecht",
    "pleidooi-voor-een-democratische-cultuur",
    "stop-de-oorlog-in-oekraine-kom-naar-de-actiebijeenkomst-28-februari",
    "geen-racisme-en-fascisme-in-de-raad-demonstratie",
    "de-bode-maart-2022-het-is-tijd-voor-solidariteit-in-de-belastingen",
    "de-bode-maart-2022-linkse-partijen-dacht-het-niet",
    "de-bode-maart-2022-huisbazen-parasieten%ef%bf%bc",
    "rood-zomerschool-de-jeugd-ontwaakt",
    "socialisten-noord-is-van-start",
    "de-rode-bode-stop-de-gaswinning",
    "de-rode-bode-huisjesmelkers-niet-aanpakken-maar-afpakken",
    "waarom-overheidssoft-ware-open-source-moet-zijn",
    "kiezen-we-voor-de-vogelgriep",
    "kapitalisme-maakt-rommel",
    "kom-naar-de-rood-groningen-filmavond",
    "opruiing-een-risico-voor-ons-allemaal",
    "rood-groningen-in-actie-voor-wij-weigeren-de-huurverhoging",
    "de-bode-april-2022-oproep-tot-een-linkse-oppositie",
    "de-bode-april-2022-ontwaakt-vier-op-1-mei-de-dag-van-de-arbeid",
    "de-bode-april-2022-kanaleneiland-en-overvecht-zijn-geen-probleemwijken-de-gemeenteraad-is-een-problemenraad",
    "op-een-onbewoond-eiland",
    "bezet-sluit-aan",
    "kind-mishandeld-door-politie-waarom-gebeurt-dit-zo-vaak",
    "de-vreemdste-gemeenteraadsverkiezingen-ooit",
    "rood-arnhem-organiseert-antifascistische-fiets-en-wandeltocht",
    "gemeente-arnhem-heeft-zelfstandig-wonende-jongmeerderjarigen-jarenlang-een-te-lage-bijstandsuitkering-gegeven",
    "alv-verslag-27-maart-2022",
    "10-stellingen-over-socialisme-en-religie",
    "conservatisme-en-religie-ken-je-kritiekpunten-2",
    "de-bode-mei-2022-coalitievorming-een-pot-nat",
    "de-bode-mei-2022-wachtlijst-drie-jaar-te-lang-tijd-voor-trans-zorg-nu",
    "weiger-de-huurverhoging-slaat-aan-minister-nodigt-huurders-uit",
    "de-klm-staking-en-wat-we-ervan-moeten-leren",
    "maak-de-waalstrandjes-weer-vrij",
    "voorwaarts-naar-een-vrije-dag-van-de-arbeid",
];

export default withTM({
    reactStrictMode: true,
    async rewrites() {
        return [
            { source: "/nieuws", destination: "/actueel" },
            { source: "/inzendingen", destination: "/actueel" },
            { source: "/petitie/:slug", destination: "/post/:slug" },
        ];
    },
    async redirects() {
        const afdelingenResponse = await backend.get("/afdelingen", {
            params: {
                sort: "name",
                fields: ["slug"],
            },
        });
        const afdelingen = afdelingenResponse.data.data;

        return [
            {
                source: "/roundcube",
                destination: "https://web0134.zxcs.nl/roundcube",
                permanent: true,
            },
            { source: "/groepen", destination: "/afdelingen", permanent: true },
            {
                source: "/groepen/:slug",
                destination: "/afdelingen/:slug",
                permanent: true,
            },
            {
                source: "/actueel",
                destination: "/posts",
                permanent: true,
            },
            {
                source: "/steun-ons",
                destination: "/word-lid",
                permanent: true,
            },
            ...postsToRedirect.map((it) => {
                return {
                    source: `/${it}`,
                    destination: `/post/${it}`,
                    permanent: true,
                };
            }),
            ...afdelingen.map((it) => {
                return {
                    source: `/${it.attributes.slug}`,
                    destination: `/afdelingen/${it.attributes.slug}`,
                    permanent: true,
                };
            }),
        ];
    },
});
